name: Test & Benchmark

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
  workflow_dispatch:
  
jobs:
  test_and_benchmark:
    name: Test and benchmark
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ref
      uses: actions/checkout@v2
    - name: Preparation
      uses: ./.github/actions/prepare
    - name: Run tests
      run: npm test
    - name: Run benchmarks
      run: npm run benchmark
